In [81]:
import torch
import numpy as np

In [2]:
torch.cuda.is_available()

False

In [3]:
# CREATING AN EMPTY TENSOR OF 0NE DIMENSIONAL VECTOR WITH 3 ELEMENTS
x = torch.empty(3)
x 

tensor([0., 0., 0.])

In [8]:
# CREATING ANOTHER EMPTY TENSOR: 2D MATRIX
x = torch.empty(2,3) # CAN ADD MORE DIMENSION TO IT LIKE torch.empty(2,2,2,3)
u = torch.empty(2,2,2,3)
u 

tensor([[[[4.2731e-05, 4.0975e-11, 6.7884e-07],
          [2.9574e-18, 6.7333e+22, 1.7591e+22]],

         [[1.7184e+25, 4.3222e+27, 6.1972e-04],
          [7.2443e+22, 1.7728e+28, 7.0367e+22]]],


        [[[1.8704e+20, 1.0682e-05, 1.2800e-11],
          [2.6405e-06, 6.5558e-10, 5.4655e+22]],

         [[2.0470e+23, 4.2963e-05, 3.3240e+21],
          [3.0926e-18, 7.7052e+31, 1.9447e+31]]]])

In [17]:
# CREATING TENSORS WITH RANDOM VALUES WITH DIFFRENT STRATEGY

c = torch.rand(
    2,2
)
print(c)
x = torch.ones(
    2,2
)
print(x)

# OR
a = torch.zeros(
    3,4,5
)
a

tensor([[0.6018, 0.6360],
        [0.3939, 0.1873]])
tensor([[1., 1.],
        [1., 1.]])


tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [31]:
# DATATYPES 
# changing DATA-TYPES

z = torch.ones( [2,1,3  ],dtype=torch.int #float16,#double)
print(z.dtype)


SyntaxError: invalid syntax (<ipython-input-31-5e9077a5475b>, line 5)

In [27]:
# CHECKING FOR THE SIZE

e = torch.zeros(3,2)
e.size()

torch.Size([3, 2])

# BASIC OPERATIONS TO PERFORM WITH TENSORS

In [46]:
ab = torch.rand(2,6)
bc = torch.rand(2,6)

### ADDITION

In [49]:
# ELEMENT WISE ADDITION
t = torch.add(ab,bc)
print(t)

# INPLACE ADDITON
w = bc.add_(ab)
print(w)

tensor([[1.9656, 0.4197, 1.1460, 0.3398, 0.7175, 0.1748],
        [2.5255, 0.9188, 2.3894, 2.0916, 0.9397, 0.7639]])
tensor([[1.9656, 0.4197, 1.1460, 0.3398, 0.7175, 0.1748],
        [2.5255, 0.9188, 2.3894, 2.0916, 0.9397, 0.7639]])


### SUBTRACTION

In [52]:
# ELEMENT WISE SUBTRACTION

a = torch.sub(ab,bc)
print(a)

#INPLACE SUBTRACTION
b= ab.sub_(bc)
print(b)

tensor([[-0.0509, -0.3715, -0.0702, -0.0310, -0.7128, -0.1005],
        [-0.7624, -0.0146, -0.7175, -0.3619, -0.6326, -0.0842]])
tensor([[-0.0509, -0.3715, -0.0702, -0.0310, -0.7128, -0.1005],
        [-0.7624, -0.0146, -0.7175, -0.3619, -0.6326, -0.0842]])


### MULTIPLICATION

In [53]:
# ELEMENT WISE MULTIPLICATION
z = torch.mul(ab,bc)
print(z)

# INPLACE MULTIPLICATION
xd = ab.mul_(bc)
print(xd)

tensor([[-0.0513, -0.1470, -0.0427, -0.0057, -0.5098, -0.0138],
        [-1.2533, -0.0068, -1.1146, -0.4440, -0.4973, -0.0357]])
tensor([[-0.0513, -0.1470, -0.0427, -0.0057, -0.5098, -0.0138],
        [-1.2533, -0.0068, -1.1146, -0.4440, -0.4973, -0.0357]])


### PERFORMRING SLICING OPERATIONS

In [73]:
xw = torch.rand(6,4)

# (xw[#ROWS:,#COLUMNS])
print(xw)
print(xw[1:,3]) #SECOND ROW AND A PARTICULAR COLUMN
print(xw[:,3]) # ALL THE ROWS AND PARTICULAR COLUMN 
print(xw[3,3]) #GET AN ELEMENT AT PARTICULAR POSITION


tensor([[0.5564, 0.2125, 0.6860, 0.3432],
        [0.4508, 0.7576, 0.2307, 0.0368],
        [0.2226, 0.1221, 0.7311, 0.8257],
        [0.8352, 0.1409, 0.2568, 0.5712],
        [0.1509, 0.0158, 0.3721, 0.5243],
        [0.3183, 0.4868, 0.0812, 0.2443]])
tensor([0.0368, 0.8257, 0.5712, 0.5243, 0.2443])
tensor([0.3432, 0.0368, 0.8257, 0.5712, 0.5243, 0.2443])
tensor(0.5712)


In [56]:
xw

tensor([[0.4836, 0.5522],
        [0.6966, 0.9375],
        [0.8546, 0.9300],
        [0.9458, 0.7859],
        [0.0697, 0.9344],
        [0.5406, 0.4580]])

### RESHAPING | RESIZING A TENSOR

In [74]:
cv = torch.rand(4,3)

tensor([[0.5037, 0.1987, 0.2121],
        [0.9223, 0.8873, 0.0149],
        [0.6654, 0.4592, 0.8790],
        [0.5622, 0.9850, 0.1652]])

In [80]:
# reshaping with the VIEW() METHOD
zz = cv.view(12)

print(zz.size())
print(zz)

# OR

ts = cv.view(-1, 4)
print(ts.size())
print(ts)

torch.Size([12])
tensor([0.5037, 0.1987, 0.2121, 0.9223, 0.8873, 0.0149, 0.6654, 0.4592, 0.8790,
        0.5622, 0.9850, 0.1652])
torch.Size([3, 4])
tensor([[0.5037, 0.1987, 0.2121, 0.9223],
        [0.8873, 0.0149, 0.6654, 0.4592],
        [0.8790, 0.5622, 0.9850, 0.1652]])


### CONVERTING 

In [88]:
# CONVERTING FROM TENSOR TO NUMPY

b = torch.ones(7)
print(b,type(b))

ds = b.numpy()
print(ds,type(ds))

tensor([1., 1., 1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [93]:
# CONVERTING FROM NUMPY TO TENSOR
v = np.ones(5)
print(v,type(v))
ed = torch.from_numpy(v)
print(ed)

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [94]:
v

array([1., 1., 1., 1., 1.])

### WORKING WITH DEVICES: CUDA & CPU



In [97]:
if torch.cuda.is_available():
    device=torch.device('cuda')
    x = torch.ones(5)
    y = torch.ones(5)
    z = x + y.to(device)
    zs = x + y
    zs = zs.to('cpu') 

In [98]:
# REQUIRES GRAD NEEDED WHEN OPTIMIZATION IS TO BE DONE ON A AVRIABLE

x = torch.zeros(4, requires_grad=True)

x

tensor([0., 0., 0., 0.], requires_grad=True)

# AUTOGRAD: GRADIENT COMPUTATION